import type { Document } from "@langchain/core/documents";
import { DocumentLoader } from "./loaders/DocumentLoader";
import { ViajesLoader } from "./loaders/ViajesLoader";
import type { IVectorStore, SearchResult } from "../utils/interfaces";
import { llmService } from "./llm/LlmService";
import { PromptBuilder } from "./llm/PromptBuilder";
import type { RagTravel } from "../utils/schemas";
import type { ChatHistoryEntry } from "./llm/PromptBuilder";

/**
 * RagResponse
 *
 * Represents the final output of a RAG query:
 * - answer generated by the LLM
 * - model used to generate the response
 */
export interface RagResponse {
  answer: string;
  model: string;
}

/**
 * RagPipeline
 *
 * Core orchestration layer for the Retrieval-Augmented Generation (RAG) system.
 *
 * Responsibilities:
 * - Ingest documents from filesystem and external APIs
 * - Store embeddings in a vector database
 * - Perform semantic search (retrieval)
 * - Build prompts with retrieved context
 * - Generate answers using an LLM
 * - Produce conversation summaries
 *
 * Acts as the central coordinator between:
 * - loaders (data ingestion)
 * - vector store (retrieval)
 * - LLM service (generation)
 */
export class RagPipeline {
  private readonly loader: DocumentLoader;
  private readonly vectorStore: IVectorStore;

  /**
   * Creates a new RAG pipeline instance.
   *
   * @param loader - Document loader for filesystem ingestion
   * @param vectorStore - Vector database implementation
   */
  constructor(loader: DocumentLoader, vectorStore: IVectorStore) {
    this.loader = loader;
    this.vectorStore = vectorStore;
  }

  /**
   * Ingests local filesystem documents into the vector store.
   *
   * Workflow:
   * 1. Load raw documents from filesystem
   * 2. Split into chunks
   * 3. Convert into embeddings
   * 4. Store in vector database
   */
  async ingestFiles(): Promise<void> {
    const docs = await this.loader.load();
    await this.vectorStore.addDocuments(docs);
  }

  /**
   * Ingests travel data from an external API into the vector store.
   *
   * Converts travel objects into embedding-ready documents using ViajesLoader.
   *
   * @param apiUrl - Endpoint that returns travel data
   */
  async ingestViajes(apiUrl: string): Promise<void> {
    const viajesLoader = new ViajesLoader(apiUrl);
    const docs = await viajesLoader.load();
    await this.vectorStore.addDocuments(docs);
  }

  /**
   * Ingests arbitrary documents into the vector store.
   *
   * Useful for:
   * - manual embeddings
   * - external pipelines
   * - testing/debugging
   *
   * @param docs - Array of LangChain Documents
   */
  async ingestDocs(docs: Document[]): Promise<void> {
    await this.vectorStore.addDocuments(docs);
  }

  /**
   * Performs a semantic similarity search without invoking an LLM.
   *
   * Useful for debugging retrieval quality.
   *
   * @param question - Query string
   * @param k - Number of results to retrieve
   * @returns Search results from the vector store
   */
  async query(question: string, k = 4): Promise<SearchResult> {
    return this.vectorStore.similaritySearch(question, k);
  }

  /**
   * Full RAG pipeline:
   * 1. Retrieves relevant documents from vector store
   * 2. Extracts contextual text
   * 3. Builds a structured prompt (history + context + travels)
   * 4. Sends prompt to LLM
   * 5. Returns generated answer
   *
   * This is the main entry point for question answering.
   *
   * @param question - User question
   * @param travels - Travel data from backend (structured context)
   * @param history - Optional conversation history
   * @param k - Number of vector search results
   * @returns Generated answer + model metadata
   */
  async queryWithRag(
    question: string,
    travels: RagTravel[],
    history?: ChatHistoryEntry[],
    k = 4,
  ): Promise<RagResponse> {
    const { documents } = await this.vectorStore.similaritySearch(question, k);
    const contexts = documents.map((d) => d.pageContent);
    const messages = PromptBuilder.buildRagPrompt(
      question,
      travels,
      contexts,
      history,
    );
    const result = await llmService.generate(messages);
    return { answer: result.content, model: result.model };
  }

  /** Genera un resumen de la conversación usando LLM. */
  async generateSummary(history: ChatHistoryEntry[]): Promise<string> {
    const messages = PromptBuilder.buildSummaryPrompt(history);
    const result = await llmService.generate(messages);
    return result.content;
  }
}
